# Generated by Django 5.2.5 on 2025-08-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
